version: '3.3'     
services:
  mysql:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: database
      MYSQL_USER: nayeem
      MYSQL_PASSWORD: 12345
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
   image: phpmyadmin/phpmyadmin
   container_name: phpmyadmin
   restart: always         
   environment:
     PMA_HOST: mysql
     PMA_PORT: 3306
     MYSQL_ROOT_PASSWORD: 12345
   ports:
     - 8080:80  
   depends_on:        
     - mysql                    
volumes:                       
  mysql_data:

